id = "powershell"
name = "PowerShell"
version = "0.3.0"
schema_version = 1
authors = ["Thanabodee Charoenpiriyakij <wingyminus@gmail.com>"]
description = "PowerShell support"
repository = "https://github.com/wingyplus/zed-powershell"

[grammars.powershell]
repository = "https://github.com/airbus-cert/tree-sitter-powershell"
commit = "b3fe65637fca35e426dc8c889d86c8724aaa73d5" # v0.24.4

[language_servers.powershell-es]
name = "PowerShell Editor Services"
languages = ["PowerShell"]
