id = "powershell"
name = "PowerShell"
version = "0.0.1"
schema_version = 1
authors = ["Thanabodee Charoenpiriyakij <wingyminus@gmail.com>"]
description = "PowerShell support"
repository = "https://github.com/zed-industries/zed"

[grammars.powershell]
repository = "https://github.com/airbus-cert/tree-sitter-powershell"
commit = "804d86fd4ad286bd0cc1c1f0f7b28bd7af6755ad"
